package HelloApp;


/**
 * HelloApp/Hello.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Hello.idl
 * Monday, April 8, 2024 12:31:46 PM CST
 */

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface Hello
