package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, April 8, 2024 12:31:46 PM CST
*/

public interface HelloOperations 
{
  String sayHello ();
  boolean isEven (int value);
} // interface HelloOperations
